baseURL = 'https://personal.ajlabarca.com/'
languageCode = 'en-us'
title = 'AJ La Barca — Photos & Hobbies'
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeout = "120s"

[params]
  defaultTheme = "dark"
  description = "Personal photography site"
  title = "AJ's Photo Gallery"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 30
  [[menu.main]]
    name = "Work →"
    url  = "https://ajlabarca.com"
    weight = 40
